# Generated by Django 5.0.2 on 2024-03-13 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='conpassword',
            new_name='conpass',
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='password',
            new_name='pswd',
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='username',
            new_name='uname',
        ),
    ]
